name       : recastnavigation
version    : 1.6.0
release    : 2
source     :
    - https://github.com/recastnavigation/recastnavigation/archive/refs/tags/v1.6.0.tar.gz : d48ca0121962fa0639502c0f56c4e3ae72f98e55d88727225444f500775c0074
license    : Zlib
component  : programming.library
summary    : Navigation-mesh Toolset for Games
description: |
    Recast is state of the art navigation mesh construction toolset for games.
setup      : |
    %cmake_ninja \
        -DBUILD_SHARED_LIBS=ON \
        -DRECASTNAVIGATION_DEMO=OFF \
        -DRECASTNAVIGATION_EXAMPLES=OFF \
        -DRECASTNAVIGATION_TESTS=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
