name       : recastnavigation
version    : 1.5.1
release    : 1
source     :
    - git|https://github.com/recastnavigation/recastnavigation.git : c5cbd53024c8a9d8d097a4371215e3342d2fdc87
license    : Zlib
component  : programming.library
summary    : Navigation-mesh Toolset for Games
description: |
    Recast is state of the art navigation mesh construction toolset for games.
setup      : |
    %cmake_ninja \
        -DBUILD_SHARED_LIBS=ON \
        -DRECASTNAVIGATION_DEMO=OFF \
        -DRECASTNAVIGATION_EXAMPLES=OFF \
        -DRECASTNAVIGATION_TESTS=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
